"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import SiteNavBar from './sitenavbar'; // Import SiteNavBar
import { UserProvider, } from './context/usercontext';
import { QuestionProvider } from './context/questioncontext';
import { DataProvider } from "./context/datacontext";
import 'bootstrap/dist/css/bootstrap.min.css';
import { NavBarProvider } from "./context/navbarcontext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <UserProvider>
        <DataProvider>
          <QuestionProvider>

            <NavBarProvider>

              <body className={`${inter.className} bodyStyles`} style={{ position: "relative" }}>
                <SiteNavBar />
                  {children}
              </body>
            </NavBarProvider>
          </QuestionProvider>
        </DataProvider>
      </UserProvider>
    </html>
  );
}
