"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import SiteNavBar from './sitenavbar'; // Import SiteNavBar
import { UserProvider, } from './context/usercontext';
import { QuestionProvider } from './context/questioncontext';
import { DataProvider } from "./context/datacontext";
import 'bootstrap/dist/css/bootstrap.min.css';
import { NavBarProvider } from "./context/navbarcontext";
import { MyNextUIProvider } from "./context/mynextuiprovider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MyNextUIProvider>
        <UserProvider>
          <DataProvider>
            <QuestionProvider>
              <NavBarProvider>
                <body className={`${inter.className} bodyStyles`} style={{ position: "relative" }}>
                  {/* Content */}
                  {children}

                  {/* Top Navbar */}
                  {/* <div style={{ position: "absolute", top: 0, left: 0, right: 0, zIndex: 1000 }}>
                    <SiteNavBar />
                  </div> */}
                </body>
              </NavBarProvider>
            </QuestionProvider>
          </DataProvider>
        </UserProvider>
      </MyNextUIProvider>
    </html>
  );
}
